# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_viewer/_resources/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(749, 501)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar_scroll_area = QtWidgets.QScrollArea(self.central_widget)
        self.sidebar_scroll_area.setWidgetResizable(True)
        self.sidebar_scroll_area.setObjectName("sidebar_scroll_area")
        self.contents = QtWidgets.QWidget()
        self.contents.setGeometry(QtCore.QRect(0, 0, 179, 481))
        self.contents.setObjectName("contents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.contents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layer_list = QtWidgets.QListWidget(self.contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layer_list.sizePolicy().hasHeightForWidth())
        self.layer_list.setSizePolicy(sizePolicy)
        self.layer_list.setMinimumSize(QtCore.QSize(0, 0))
        self.layer_list.setObjectName("layer_list")
        self.verticalLayout.addWidget(self.layer_list)
        self.thumbnail_area = QtWidgets.QWidget(self.contents)
        self.thumbnail_area.setObjectName("thumbnail_area")
        self.verticalLayout.addWidget(self.thumbnail_area)
        self.option_area = QtWidgets.QWidget(self.contents)
        self.option_area.setObjectName("option_area")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.option_area)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.option_area)
        self.sidebar_scroll_area.setWidget(self.contents)
        self.horizontalLayout.addWidget(self.sidebar_scroll_area)
        self.grid_area = QtWidgets.QWidget(self.central_widget)
        self.grid_area.setObjectName("grid_area")
        self.horizontalLayout.addWidget(self.grid_area)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Activation Atlas Viewer"))
